AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  searchphotos:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: index-photos-lambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./search-photos
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::145273014019:role/service-role/index-photos_LF1-role-7jcliwsm'
      Environment:
        Variables:
          REGION: us-east-1
  indexphotos:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: search-photos-lambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./index-photos
      Description: "Lambda for indexing photos"
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::145273014019:role/service-role/search-photos_LF2-role-7g6hylc1'
      Environment:
        Variables:
          REGION: us-east-1
